import type { LinkingOptions } from '@react-navigation/native';

export const linking: LinkingOptions<any> = {
  prefixes: ['underdawgs://'],
  config: {
    screens: {
      Splash: 'splash',
      Onboarding: {
        screens: {
          Welcome: 'welcome',
          Auth: 'auth',
          Otp: 'otp',
          UserType: 'user-type',
          CreatorType: 'creator-type',
          Identity: 'identity',
          Complete: 'complete',
        },
      },
      Tabs: {
        screens: {
          Feed: 'feed',
          Explore: 'explore',
          Create: 'create',
          Inbox: 'inbox',
          Profile: 'profile',
        },
      },
      Modules: {
        screens: {
          Camera: 'camera',
          SettingsIndex: 'settings',
          SettingsAccount: 'settings/account',
          SettingsNotifications: 'settings/notifications',
          SettingsPrivacy: 'settings/privacy',
          SettingsSecurity: 'settings/security',
          StudioIndex: 'studio',
          StudioDrafts: 'studio/drafts',
          StudioSchedule: 'studio/schedule',
          StudioImageComposer: 'studio/image-composer',
          StudioTextComposer: 'studio/text-composer',
          StudioVideoComposer: 'studio/video-composer',
          ArtIndex: 'art',
          ArtList: 'art/list',
          ArtCommissions: 'art/commissions',
          ArtDetail: 'art/:id',
          LearningIndex: 'learning',
          LearningCourse: 'learning/:course',
          JobsIndex: 'jobs',
          JobsActiveDeals: 'jobs/active-deals',
          JobsRateCard: 'jobs/rate-card',
          JobsApply: 'jobs/apply',
          JobDetail: 'jobs/:id',
          CommunityIndex: 'community',
          CommunityEvents: 'community/events',
          CommunityGroups: 'community/groups',
          ChallengesIndex: 'community/challenges',
          ChallengeDetail: 'community/challenges/:id',
          InboxThread: 'inbox/:id',
          PortfolioIndex: 'portfolio',
          PortfolioEdit: 'portfolio/edit',
          PortfolioPieceEditor: 'portfolio/piece-editor',
          PortfolioPublicPreview: 'portfolio/public-preview',
          ReputationIndex: 'reputation',
          ReputationBadges: 'reputation/badges',
          ReputationVerification: 'reputation/verification',
          FinanceIndex: 'finance',
          FinancePayouts: 'finance/payouts',
          FinanceTransactions: 'finance/transactions',
          FinanceTax: 'finance/tax',
          FinanceInvoice: 'finance/invoice',
          MerchIndex: 'merch',
          MerchStore: 'merch/store',
          MerchCreate: 'merch/create',
          MerchOrders: 'merch/orders',
          AudienceIndex: 'audience',
          AudienceConnections: 'audience/connections',
          AudienceTopFans: 'audience/top-fans',
          AudienceEmailList: 'audience/email-list',
          AudienceLandingPage: 'audience/landing-page',
          AnalyticsIndex: 'analytics',
          AnalyticsAiInsights: 'analytics/ai-insights',
          AnalyticsContentPerformance: 'analytics/content-performance',
          AnalyticsCrossPlatform: 'analytics/cross-platform',
        },
      },
    },
  },
};
