import type { LinkingOptions } from '@react-navigation/native';

export const linking: LinkingOptions<any> = {
  prefixes: ['underdawgs://'],
  config: {
    screens: {
      Splash: 'splash',
      Onboarding: {
        screens: {
          Welcome: 'welcome',
          Auth: 'auth',
          Otp: 'otp',
          UserType: 'user-type',
          CreatorType: 'creator-type',
          Identity: 'identity',
        },
      },
      Tabs: {
        screens: {
          Feed: 'feed',
          Explore: 'explore',
          Create: 'create',
          Inbox: 'inbox',
          Profile: 'profile',
        },
      },
      Modules: {
        screens: {
          Camera: 'camera',
          SettingsIndex: 'settings',
          SettingsAccount: 'settings/account',
          SettingsNotifications: 'settings/notifications',
          SettingsPrivacy: 'settings/privacy',
          SettingsSecurity: 'settings/security',
          SettingsHelp: 'settings/help',
          SettingsBlocked: 'settings/blocked',
          StudioIndex: 'studio',
          StudioContent: 'studio/content',
          StudioDrafts: 'studio/drafts',
          StudioSchedule: 'studio/schedule',
          StudioImageComposer: 'studio/image-composer',
          StudioTextComposer: 'studio/text-composer',
          StudioAudioComposer: 'studio/audio-composer',
          StudioLiveComposer: 'studio/live-composer',
          ArtIndex: 'art',
          ArtList: 'art/list',
          ArtCommissions: 'art/commissions',
          ArtDetail: 'art/:id',
          LearningIndex: 'learning',
          LearningCourse: 'learning/:course',
          JobsIndex: 'jobs',
          JobsActiveDeals: 'jobs/active-deals',
          JobsRateCard: 'jobs/rate-card',
          JobsApply: 'jobs/apply',
          JobsApplications: 'jobs/applications',
          GigNegotiation: 'jobs/negotiation',
          GigContract: 'jobs/contract',
          GigDeliver: 'jobs/deliver',
          GigPayment: 'jobs/payment',
          JobDetail: 'jobs/:id',
          CommunityIndex: 'community',
          CommunityIntro: 'community/intro',
          CommunityEvents: 'community/events',
          CommunityEventDetail: 'community/event',
          CommunityGroups: 'community/groups',
          CommunityGroupDetail: 'community/group',
          CommunityDirectory: 'community/directory',
          CommunityMentorship: 'community/mentorship',
          CommunityQA: 'community/qa',
          ChallengesIndex: 'community/challenges',
          ChallengeDetail: 'community/challenges/:id',
          ChallengeReel: 'community/challenges/:id/reel',
          InboxThread: 'inbox/:id',
          PortfolioIndex: 'portfolio',
          PortfolioEdit: 'portfolio/edit',
          PortfolioPieceEditor: 'portfolio/piece-editor',
          PortfolioPublicPreview: 'portfolio/public-preview',
          ProfileEdit: 'profile/edit',
          ReputationIndex: 'reputation',
          ReputationBadges: 'reputation/badges',
          ReputationVerification: 'reputation/verification',
          FinanceIndex: 'finance',
          FinancePayouts: 'finance/payouts',
          FinanceTransactions: 'finance/transactions',
          FinanceTax: 'finance/tax',
          FinanceInvoice: 'finance/invoice',
          FinancePaymentMethods: 'finance/payment-methods',
          MerchIndex: 'merch',
          MerchStore: 'merch/store',
          MerchCreate: 'merch/create',
          MerchOrders: 'merch/orders',
          MerchMockup: 'merch/mockup',
          MerchAnalytics: 'merch/analytics',
          MerchDesigners: 'merch/designers',
          MerchStudio: 'merch/studio',
          MerchStudioReview: 'merch/build/review',
          MerchStudioStep1: 'merch/build/identity',
          MerchStudioStep2: 'merch/build/theme',
          MerchStudioStep3: 'merch/build/banner',
          MerchStudioStep4: 'merch/build/layout',
          MerchStudioStep5: 'merch/build/products',
          MerchStudioStep6: 'merch/build/mockups',
          MerchPublished: 'merch/build/published',
          MerchPreview: 'merch/preview',
          AudienceIndex: 'audience',
          AudienceConnections: 'audience/connections',
          AudienceTopFans: 'audience/top-fans',
          AudienceEmailList: 'audience/email-list',
          AudienceLandingPage: 'audience/landing-page',
          AnalyticsIndex: 'analytics',
          AnalyticsAiInsights: 'analytics/ai-insights',
          AnalyticsContentPerformance: 'analytics/content-performance',
          AnalyticsCrossPlatform: 'analytics/cross-platform',
          AnalyticsEarnings: 'analytics/earnings',
          AnalyticsAudience: 'analytics/audience',
          TipsIndex: 'tips',
          CollabIndex: 'collab',
          CollabSend: 'collab/send',
          CollabRequestDetail: 'collab/request',
          ProfileVisibility: 'profile/visibility',
        },
      },
    },
  },
};
